"""add project status

Revision ID: 800e5ec06b1f
Revises: 41c4c8adeac8
Create Date: 2026-09-07 18:17:32.065177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800e5ec06b1f'
down_revision: Union[str, Sequence[str], None] = '41c4c8adeac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
